Refactor pre-push and commit-msg

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -17,8 +17,27 @@
 
 # This example catches duplicate Signed-off-by lines.
 
-test "" = "$(grep '^Signed-off-by: ' "$1" |
-	 sort | uniq -c | sed -e '/^[ 	]*1[ 	]/d')" || {
-	echo >&2 Duplicate Signed-off-by lines.
-	exit 1
-}
+Color_Off='\033[0' 
+BRed="\033[1;31m"         # Red
+BGreen="\033[1;32m"       # Green
+BYellow="\033[1;33m"      # Yellow
+BBlue="\033[1;34m"
+
+MSG_FILE=$1
+FILE_CONTENT="$(cat $MSG_FILE)"
+
+export ERROR_MSG="First line of commit message longer than 72 character"
+
+IFS="\n" read -a MESSAGE_LINES <<< "$FILE_CONTENT"
+
+FIRST_LINE_MESSAGE="${MESSAGE_LINES[0]}"
+
+if [[ ${#FIRST_LINE_MESSAGE} -le 72 ]]; then
+ 	echo "${BGreen}Good commit!${Color_Off}"
+ exit 0
+else
+	echo "${BRed}Bad commit ${BYellow}\"$FIRST_LINE_MESSAGE\"\n"
+ 	echo "${BBlue}$ERROR_MSG\n"
+ exit 1
+fi
+
