Refactor commit-msg and pre-push

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -17,13 +17,13 @@
 
 # This example catches duplicate Signed-off-by lines.
 
-Color_Off='\033[0' 
-BRed="\033[1;31m"         # Red
-BGreen="\033[1;32m"       # Green
-BYellow="\033[1;33m"      # Yellow
+Color_Off='\033[0'
+BRed="\033[1;31m"    # Red
+BGreen="\033[1;32m"  # Green
+BYellow="\033[1;33m" # Yellow
 BBlue="\033[1;34m"
 
-function check_commit_message(){
+function check_commit_message() {
 
 	export ERROR_MSG="First line of commit message longer than 72 character"
 
@@ -31,7 +31,7 @@ function check_commit_message(){
 
 	# -r disallows escape sequences, line condition
 
-	IFS=$'\n' read -r -d '' -a MESSAGE_LINES <<< $COMMIT_MESSAGE
+	IFS=$'\n' read -r -d '' -a MESSAGE_LINES <<<$COMMIT_MESSAGE
 
 	COMMIT_MESSAGE_LINES="$MESSAGE_LINES"
 
@@ -39,28 +39,26 @@ function check_commit_message(){
 
 	#If this script exits non-zero, Git aborts the commit process
 
-	if [ ${#FIRST_LINE_MESSAGE} -le 72 ];
-	then
- 		printf "${BGreen}Good commit!${Color_Off}\n"
- 		exit 0
+	if [ ${#FIRST_LINE_MESSAGE} -le 72 ]; then
+		printf "${BGreen}Good commit!${Color_Off}\n"
+		exit 0
 	else
 		printf "${BRed}Bad commit: ${BYellow}'%s'\n" $FIRST_LINE_MESSAGE
- 		printf "${BBlue}$ERROR_MSG\n"
- 		exit 1
+		printf "${BBlue}$ERROR_MSG\n"
+		exit 1
 	fi
 }
 
-# The commit-msg hook takes one parameter, which again is the path to a temporary file that contains the commit message written by the developer. 
+# The commit-msg hook takes one parameter, which again is the path to a temporary file that contains the commit message written by the developer.
 
 TEMPORARY_MSG_FILE=$1
 FILE_CONTENT=$(cat $TEMPORARY_MSG_FILE)
 
 # Check FILE_CONTENT is not empty
 
-if [[ $FILE_CONTENT ]]
-then
+if [[ $FILE_CONTENT ]]; then
 	check_commit_message "$FILE_CONTENT"
 else
 	printf "Please enter commit message\n"
 	exit 1
-fi	
+fi
diff --git a/pre-push b/pre-push
--- a/pre-push
+++ b/pre-push
@@ -1,4 +1,4 @@
-#!/bin/sh 
+#!/bin/sh
 
 # An example hook script to verify what is about to be pushed.  Called by "git
 # push" after it has checked the remote status, but before anything has been
@@ -19,72 +19,100 @@
 # This sample shows how to prevent push of commits where the log message starts
 # with "WIP" (work in progress).
 
-# Get branch nameset -x	
+# Get branch nameset -x
 
-function runStaticCheck(){
+function checkKtlintResult() {
 
- echo "Runnig static analysis..."
+	# Check static analysis result
 
- ./gradlew app:ktlintCheck app:detektCheck --daemon
+	local KTLINT_CHECK_STATUS=$1
 
-# Check ktlint status
- local STATIC_CHECK_STATUS=$?
+	if [[ "$KTLINT_CHECK_STATUS" -eq 0 ]]; then
+		echo "ktlint found no problems."
 
- if [ "$STATIC_CHECK_STATUS" -eq 0 ]
- then
-	printf "Static analysis found no problems.\n"
-	askUnitTest
- else 
-	printf "Static analysis find these issues\n"	
-	printf 1>&2 
-	exit 1
- fi
+		runDetektCheck
+
+	else
+		echo "ktlint find these issues"
+		echo 1>&2
+		askForFormatCode
+		exit 1
+	fi
 
 }
 
-function runUnitTests(){
+function runDetektCheck() {
 
- printf "Running unit tests\n"
+	echo "Running detekt"
 
- ./gradlew clean test
+	./gradlew detektCheck --daemon
 
- #Check unit test status
- local UNIT_TEST_STATUS=$?
+	local DETEKT_CHECK_STATUS=$?
 
- if [ "$UNIT_TEST_STATUS" -eq 0 ]
- then
-	printf "All unit tests passed\n"
-	exit 0
- else
-	printf "Unit tests failed\n"
-	printf 1>&2
-	exit 1
- fi
+	if [[ "$DETEKT_CHECK_STATUS" -eq 0 ]]; then
+		echo "detekt found no problems."
+
+		askUnitTest
+	else
+		echo "detekt find these issues"
+		echo 1>&2
+		askForFormatCode
+		exit 1
+	fi
+
 }
 
-function askUnitTest(){
+function runUnitTests() {
+
+	echo "Running unit tests"
+
+	./gradlew clean test
+
+	#Check unit test status
+
+	local UNIT_TEST_STATUS=$?
+
+	if [[ $UNIT_TEST_STATUS -eq 0 ]]; then
+		echo "All unit tests passed"
+		exit 0
+	else
+		echo "Unit tests failed"
+		echo 1>&2
+		exit 1
+	fi
+}
+
+function askUnitTest() {
 
 	read -p "Do you want to run unit test? Y or N" UNIT_TEST_ANSWER
 
-	case $UNIT_TEST_ANSWER in 
-	[yY])
+	if [[ $UNIT_TEST_ANSWER = [yY] ]]; then
 		runUnitTests
-	;;
-	*)
-		printf "Unit tests are not running\n"
-		exit 0	
-	;;
-
-	esac
+	else
+		echo "Unit tests are not running"
+		exit 0
+	fi
 }
 
-BRANCH=`git rev-parse --abbrev-ref HEAD`
+function askForFormatCode() {
+
+	read -p "Do you want to format code? Y or N" FORMAT_CODE_RESULT
+
+	if [[ $FORMAT_CODE_RESULT = [yY] ]]; then
+		./gradlew ktlintFormat
+	else
+		echo "Code format is not running"
+		exit 0
+	fi
+
+}
 
 #A non-zero exit code will abort the push
 
-if [ "$BRANCH" -ne "wip/*" ]
-then
-	
-	runStaticChecks	
-	
-fi	
+echo "Runnig ktlint..."
+
+./gradlew ktlintCheck --daemon
+
+checkKtlintResult
+
+exit 0
