-Refactor unit test running logic into pre-hook hook file  - Add method for commit message check and add control for empty commit message into commit-msg hook file

diff --git a/commit-msg b/commit-msg
--- a/commit-msg
+++ b/commit-msg
@@ -23,22 +23,33 @@ BGreen="\033[1;32m"       # Green
 BYellow="\033[1;33m"      # Yellow
 BBlue="\033[1;34m"
 
+fun check_commit_message(){
+
+	export ERROR_MSG="First line of commit message longer than 72 character"
+
+	IFS="\n" read -a MESSAGE_LINES <<< "$1"
+	set -x
+
+	local FIRST_LINE_MESSAGE="${MESSAGE_LINES[0]}"
+
+	if [[ ${#FIRST_LINE_MESSAGE} -le 72 ]];
+	then
+ 		echo "${BGreen}Good commit!${Color_Off}"
+ 		exit 0
+	else
+		echo "${BRed}Bad commit ${BYellow}\"$FIRST_LINE_MESSAGE\"\n"
+ 		echo "${BBlue}$ERROR_MSG\n"
+ 		exit 1
+	fi
+	set +x
+}
+
 MSG_FILE=$1
 FILE_CONTENT="$(cat $MSG_FILE)"
 
-export ERROR_MSG="First line of commit message longer than 72 character"
-
-IFS="\n" read -a MESSAGE_LINES <<< "$FILE_CONTENT"
-
-FIRST_LINE_MESSAGE="${MESSAGE_LINES[0]}"
-
-if [[ ${#FIRST_LINE_MESSAGE} -le 72 ]];
+if [ -z "$FILE_CONTENT" ]
 then
- 	echo "${BGreen}Good commit!${Color_Off}"
- exit 0
+	check_commit_message $FILE_CONTENT
 else
-	echo "${BRed}Bad commit ${BYellow}\"$FIRST_LINE_MESSAGE\"\n"
- 	echo "${BBlue}$ERROR_MSG\n"
- exit 1
-fi
-
+	echo "Please enter commit message"
+fi	
